#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Apr 30 10:03:08 EDT 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -view /home/ericdong/workspace/test_accel/test_accel.srcs/sim_1/imports/test/top_behav.wcfg -log simulate.log"
xsim top_behav -key {Behavioral:sim_1:Functional:top} -tclbatch top.tcl -view /home/ericdong/workspace/test_accel/test_accel.srcs/sim_1/imports/test/top_behav.wcfg -log simulate.log

