#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Wed Apr 05 04:22:54 EDT 2023
# SW Build 3247384 on Thu Jun 10 19:36:07 MDT 2021
#
# IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim accelerator_tb_behav -key {Behavioral:sim_1:Functional:accelerator_tb} -tclbatch accelerator_tb.tcl -protoinst "protoinst_files/bd_22e4.protoinst" -protoinst "protoinst_files/pci_mig.protoinst" -view /home/ericdong/workspace/pci_mig/accelerator_tb_behav.wcfg -log simulate.log"
xsim accelerator_tb_behav -key {Behavioral:sim_1:Functional:accelerator_tb} -tclbatch accelerator_tb.tcl -protoinst "protoinst_files/bd_22e4.protoinst" -protoinst "protoinst_files/pci_mig.protoinst" -view /home/ericdong/workspace/pci_mig/accelerator_tb_behav.wcfg -log simulate.log

